[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=5MB
logfile_backups=3
pidfile=/var/run/supervisord.pid

[program:laravel-serve]
directory=/var/www/html
command=/usr/bin/php artisan serve --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/serve-stdout.log
stderr_logfile=/var/log/supervisor/serve-stderr.log
stopasgroup=true
killasgroup=true

[program:laravel-scheduler]
directory=/var/www/html
command=/bin/sh -c "/usr/local/bin/schedule.sh"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/schedule-stdout.log
stderr_logfile=/var/log/supervisor/schedule-stderr.log
stopasgroup=true
killasgroup=true
